// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	"github.com/Xanaduxan/tasks-golang/task-service/internal/events"
	mock "github.com/stretchr/testify/mock"
)

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

// NotifyTaskStatusUpdated provides a mock function with given fields: event
func (_m *Notifier) NotifyTaskStatusUpdated(event events.TaskStatusUpdated) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for NotifyTaskStatusUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(events.TaskStatusUpdated) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
