version: "3.9"

services:
  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      DATABASE_URL: ${TASKS_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      HTTP_PORT: ${HTTP_PORT}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      NOTIFICATION_ADDR: ${NOTIFICATION_ADDR}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    depends_on:
      - db
      - redis
      - notification-service
      - kafka
  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8083:8080"
      - "50053:50053"
    environment:
      DATABASE_URL: ${PAYMENTS_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      HTTP_PORT: ${HTTP_PORT}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      NOTIFICATION_ADDR: ${NOTIFICATION_ADDR}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    depends_on:
      - payments-db
      - redis
      - notification-service
      - kafka

  etl-worker:
    build:
      context: .
      dockerfile: etl-worker/Dockerfile
    environment:
      DATABASE_URL: ${TASKS_DATABASE_URL}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
    depends_on:
      - db
      - kafka

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8081:8081"
      - "50052:50052"

  db:
    container_name: tasks-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: taskspass
    ports:
      - "5432:5432"
    volumes:
      - tasks_pgdata:/var/lib/postgresql/data
      - ./task-service/migrations:/docker-entrypoint-initdb.d

  payments-db:
    container_name: payments-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: paymentspass
    ports:
      - "5433:5432"
    volumes:
      - payments_pgdata:/var/lib/postgresql/data
      - ./payments-service/migrations:/docker-entrypoint-initdb.d


  redis:
    image: redis:7
    ports:
      - "6379:6379"

  redis-ui:
    image: rediscommander/redis-commander
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis

  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

volumes:
  tasks_pgdata:
  payments_pgdata: