// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	storage "github.com/Xanaduxan/tasks-golang/internal/storage"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// GroupMemberInterface is an autogenerated mock type for the GroupMemberInterface type
type GroupMemberInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: member
func (_m *GroupMemberInterface) Create(member storage.GroupMember) error {
	ret := _m.Called(member)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(storage.GroupMember) error); ok {
		r0 = rf(member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: groupID, userID
func (_m *GroupMemberInterface) DeleteByID(groupID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByGroupID provides a mock function with given fields: groupID
func (_m *GroupMemberInterface) GetByGroupID(groupID uuid.UUID) ([]storage.GroupMember, error) {
	ret := _m.Called(groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetByGroupID")
	}

	var r0 []storage.GroupMember
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]storage.GroupMember, error)); ok {
		return rf(groupID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []storage.GroupMember); ok {
		r0 = rf(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.GroupMember)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: groupID, userID
func (_m *GroupMemberInterface) GetByID(groupID uuid.UUID, userID uuid.UUID) (storage.GroupMember, error) {
	ret := _m.Called(groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 storage.GroupMember
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (storage.GroupMember, error)); ok {
		return rf(groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) storage.GroupMember); ok {
		r0 = rf(groupID, userID)
	} else {
		r0 = ret.Get(0).(storage.GroupMember)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsMember provides a mock function with given fields: groupID, userID
func (_m *GroupMemberInterface) IsMember(groupID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(groupID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: member
func (_m *GroupMemberInterface) Update(member storage.GroupMember) error {
	ret := _m.Called(member)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(storage.GroupMember) error); ok {
		r0 = rf(member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGroupMemberInterface creates a new instance of GroupMemberInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupMemberInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupMemberInterface {
	mock := &GroupMemberInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
