// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	storage "github.com/Xanaduxan/tasks-golang/internal/storage"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// UserInterface is an autogenerated mock type for the UserInterface type
type UserInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *UserInterface) Create(user storage.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(storage.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: id
func (_m *UserInterface) DeleteByID(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByEmail provides a mock function with given fields: email
func (_m *UserInterface) GetByEmail(email string) (storage.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 storage.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (storage.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) storage.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(storage.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *UserInterface) GetByID(id uuid.UUID) (storage.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 storage.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (storage.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) storage.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(storage.User)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserInterface creates a new instance of UserInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInterface {
	mock := &UserInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
