// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	"github.com/Xanaduxan/tasks-golang/task-service/internal/storage"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// GroupInterface is an autogenerated mock type for the GroupInterface type
type GroupInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: group
func (_m *GroupInterface) Create(group storage.Group) error {
	ret := _m.Called(group)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(storage.Group) error); ok {
		r0 = rf(group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *GroupInterface) GetByID(id uuid.UUID) (storage.Group, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 storage.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (storage.Group, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) storage.Group); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(storage.Group)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGroupInterface creates a new instance of GroupInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupInterface {
	mock := &GroupInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
